# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UOiOSDevelopmentClub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UOiOSDevelopmentClub

    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'FirebaseCore'
    pod 'Firebase/Firestore'


  target 'UOiOSDevelopmentClubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UOiOSDevelopmentClubUITests' do
    # Pods for testing
  end

end
